spring:
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: sihao
    password: dong
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    database: 0
    host: localhost
    port: 6379
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml